version: "3"
services:
  gcs:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - ./haremovie-storage:/data/${GOOGLE_STORAGE_BUCKET_NAME}
    command:
      ["-scheme", "http", "-port", "4443", "-external-url", "http://gcs:4443"]
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/${GOOGLE_CLOUD_PROJECT}/locations/${GOOGLE_CLOUD_LOCATION}/queues/haremovie-agent-queue"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:8080
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  haremovie_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: haremovie_api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
      - HAREMOVIE_WORKER_URL=http://worker:8001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    env_file:
      - .env
    depends_on:
      - gcs
      - gcloud-tasks-emulator
      - db
  worker:
    image: haremovie_api:latest
    command: ["fastapi", "run", "src/haremovie_api/worker.py", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    env_file:
      - .env
    depends_on:
      - gcs
      - db
      - gcloud-tasks-emulator
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db_data:
